# Change these first
owner: appsumo # Your GitHub organization or username, where this repository lives
repo: updates # The name of this repository

sites: []

status-website:
  theme: light
  cname: updates.appsumo.com
  logoUrl: https://updates.appsumo.com/logo.svg
  favicon: https://updates.appsumo.com/favicon.png
  faviconSvg: https://updates.appsumo.com/logo.svg
  name: Updates
  introTitle: ""
  introMessage: 
  links:
    - rel: stylesheet
      href: https://updates.appsumo.com/custom-styles.css
  navbar:
    - title: Status
      href: /
    - title: AppSumo
      href: https://appsumo.com


i18n:
  footer: "AppSumo Updates"