# Change these first
owner: appsumo # Your GitHub organization or username, where this repository lives
repo: updates # The name of this repository

sites:
  - name: AppSumo
    url: https://appsumo.com

status-website:
  theme: light
  cname: updates.appsumo.com
  logoUrl: https://appsumo2next-cdn.appsumo.com/_next/static/media/as-appsumo-logo-dark.fbc325ee.svg
  favicon: https://example.com/favicon.png
  faviconSvg: https://example.com/logo.svg
  name: AppSumo Updates
  introTitle: "AppSumo Updates"
  introMessage: 
  navbar:
    - title: Status
      href: /
